### ISSUE TITLE
Not working (?)

### ISSUE THREAD

**Issue by Wuerike** [RustyJoeM/docx-template-filler#2]
I've done the build and tested it with the example template, but all the 3 generated files came with the tokens instead of the desired values.

![image](https://user-images.githubusercontent.com/35462243/211225496-9c6ab68b-9996-47aa-9162-e636478d1ca7.png)

**Comment by RustyJoeM** [comment]
Hmm, i've tested it now and it works for me in "clean" state for both debug and release build.
(checkout from repository, build, using template docx, adding a line "`Bob; birthday; 1.1.2022; John Doe`").

As the app itself is very pritmitive (not taking more complex cases into account), problem you see could be due to various reasons.

Can you check e.g. [limitations](https://github.com/RustyJoeM/docx-template-filler/blob/main/manual.md#limitations) in the manual, and make sure that the tokens were not "mangled" when exiting/saving template doc on your side?
You can also verify this by opening the doc template file that you want to use for filling in some archive manager (doc is internally "zip" archive):
and see the file "`word/document.xml`" inside of archive -> it has to contain the template strings like "`{{PERSON}}`" etc.

I have not tested it with other versions of ms word document format, so this could be reason as well.
I can try to check on the problem, but i'll need an example/reproducible scenario - e.g. what version of word document you used to save template, and exact text line that you entered into running app to fill in...
